name = "ebay-api-backend-2"
main = "src/index.ts"
compatibility_date = "2024-11-01"

[vars]
EBAY_ENV = "production"


# Uncomment and fill if you create a KV namespace for token reuse
# [[kv_namespaces]]
# binding = "TOKEN_CACHE"
# id = "<kv-id>"
