name = "ebay-api-worker"
main = "src/index.ts"
compatibility_date = "2026-01-27"

[vars]
EBAY_ENV = "production"

# -----------------------------
# KV RATE LIMITER
# -----------------------------
[[kv_namespaces]]
binding = "RATE_LIMITER"
id = "a584ab29b3f744a09c2d5132f8dd1636"
